FROM python:3.12-slim

ARG APP_VERSION=0.1.1
ENV APP_VERSION=${APP_VERSION}

RUN apt-get update && apt-get install -y \
    curl unzip git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD --checksum=sha256:47fe12da6118698bbea0ec1bb6f174b9b33540c1643119d41dd2046d2f37e6c7 \
    https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/${APP_VERSION}.zip /tmp/app.zip

RUN unzip /tmp/app.zip && \
    mv StaticJinjaPlus-${APP_VERSION}/* . && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    rm -rf /tmp/app.zip StaticJinjaPlus-${APP_VERSION}

CMD ["python", "main.py"]
